### ISSUE TITLE
Support bulk IPFS pinning and/or pinning at mint

### ISSUE THREAD

**Issue by psiemens** [onflow/freshmint#42]
Users currently have to call `fresh pin X` on each individual NFT that they have minted. This is tedious and time consuming. 

A few alternatives:

**1. Bulk pinning**

This is useful for users that want to reveal IPFS assets _after_ minting.

```sh
# Loop through all NFTs and pin their assets to IPFS
fresh pin --all
```

**2. Pinning on mint**

This is useful for users who do not need to hide assets at the time of mint.

```sh
# Pin each NFT to IPFS at the time of minting
fresh mint --pin
```

**Comment by psiemens** [comment]
@conorao I know you mentioned that a feature like this would be useful to you. Would you prefer option 1 or 2 above?

**Comment by conorao** [comment]
@psiemens I think option 1 would be more flexible - because you'd be able to not only allow for revealing assets after minting, but implement option 2 as well by just cascading the 
```bash
fresh mint 
```
and 
```bash
fresh pin --all
```
commands, right?

**Comment by psiemens** [comment]
Yep that should accomplish the same thing!
